name: Actualizare Curs EUR
on:
  schedule:
    - cron: '0 7 * * *' # Rulează zilnic la ora 7:00 AM
  workflow_dispatch: # Permite declanșare manuală din buton

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: node update-eur.js
        env:
          SHOPIFY_SHOP: ${{ secrets.SHOPIFY_SHOP }}
          SHOPIFY_TOKEN: ${{ secrets.SHOPIFY_TOKEN }}
